import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';
import type { Produto, Venda, Receita, Notificacao, TipoNotificacao, SessaoTenant } from '../types';
import { tenantIdDoUsuario } from '../types';
import { supabase } from '../lib/supabaseClient';
import { produtoDoBanco, produtoParaBanco, receitaDoBanco, receitaParaBanco, vendaDoBanco, ingredienteDoBanco } from '../lib/mappers';

interface AppContextValue {
 produtos: Produto[]; receitas: Receita[]; vendas: Venda[]; carregando: boolean; erroConexao: string | null; sessao: SessaoTenant | null;
 notificacoes: Notificacao[]; setNotificacoes: React.Dispatch<React.SetStateAction<Notificacao[]>>; adicionarNotificacao: (mensagem:string,tipo?:TipoNotificacao)=>void; nomeProdutoExiste:(nome:string,ignorarId?:string)=>boolean;
 criarProduto:(dados:Omit<Produto,'id'>)=>Promise<boolean>; atualizarProduto:(p:Produto)=>Promise<boolean>; excluirProduto:(id:string)=>Promise<boolean>; criarReceita:(dados:Omit<Receita,'id'>)=>Promise<boolean>; excluirReceita:(id:string)=>Promise<boolean>; darBaixa:(id:string,tipo:'ML'|'Unidade',qtd:number)=>Promise<boolean>; registrarVenda:(v:Omit<Venda,'id'>)=>Promise<boolean>; entrar:(email:string,senha:string)=>Promise<boolean>; sair:()=>Promise<void>;
}
const AppContext=createContext<AppContextValue|null>(null);
export function AppProvider({children}:{children:ReactNode}){
 const [produtos,setProdutos]=useState<Produto[]>([]),[receitas,setReceitas]=useState<Receita[]>([]),[vendas,setVendas]=useState<Venda[]>([]),[notificacoes,setNotificacoes]=useState<Notificacao[]>([]),[carregando,setCarregando]=useState(true),[erroConexao,setErroConexao]=useState<string|null>(null),[sessao,setSessao]=useState<SessaoTenant|null>(null);
 const adicionarNotificacao=(mensagem:string,tipo:TipoNotificacao='aviso')=>{const id=crypto.randomUUID();setNotificacoes(p=>[...p,{id,mensagem,tipo}]);window.setTimeout(()=>setNotificacoes(p=>p.filter(n=>n.id!==id)),6000)};
 const carregar=async()=>{setCarregando(true);const {data:{user}}=await supabase.auth.getUser();const tenantId=tenantIdDoUsuario(user);if(!user||!tenantId){setSessao(null);setCarregando(false);return}setSessao({id:user.id,email:user.email,nome:String(user.user_metadata?.nome??user.email?.split('@')[0]??''),tenantId,cargo:String(user.user_metadata?.cargo??'caixa')});const [p,r,v]=await Promise.all([supabase.from('produtos').select('*').order('nome'),supabase.from('receitas').select('*').order('nome'),supabase.from('vendas').select('*').order('data_hora',{ascending:false})]);const error=p.error??r.error??v.error;if(error){setErroConexao('Não foi possível carregar os dados do tenant atual.');adicionarNotificacao('Falha ao carregar dados: '+error.message,'erro')}else{setProdutos((p.data??[]).map(produtoDoBanco));const ing=(await supabase.from('receita_ingredientes').select('*')).data??[];setReceitas((r.data??[]).map(row=>receitaDoBanco(row,ing.filter(i=>i.receita_id===row.id).map(i=>ingredienteDoBanco(i,(p.data??[]).map(produtoDoBanco).find(x=>x.id===i.produto_id))))));setVendas((v.data??[]).map(vendaDoBanco))}setCarregando(false)};
 useEffect(()=>{carregar();const {data}=supabase.auth.onAuthStateChange(()=>{void carregar()});return()=>data.subscription.unsubscribe()},[]);
 const nomeProdutoExiste=(nome:string,ignorarId?:string)=>produtos.some(p=>p.id!==ignorarId&&p.nome.trim().toLowerCase()===nome.trim().toLowerCase());
 const criarProduto=async(d:Omit<Produto,'id'>)=>{if(!sessao?.tenantId)return false;const {data,error}=await supabase.from('produtos').insert({...produtoParaBanco(d),tenant_id:sessao.tenantId}).select().single();if(error||!data){adicionarNotificacao('Erro ao salvar produto.','erro');return false}setProdutos(p=>[...p,produtoDoBanco(data)]);return true};
 const atualizarProduto=async(p:Produto)=>{const {data,error}=await supabase.from('produtos').update(produtoParaBanco(p)).eq('id',p.id).select().single();if(error||!data){adicionarNotificacao('Erro ao atualizar produto.','erro');return false}setProdutos(xs=>xs.map(x=>x.id===p.id?produtoDoBanco(data):x));return true};
 const excluirProduto=async(id:string)=>{const {error}=await supabase.from('produtos').delete().eq('id',id);if(error){adicionarNotificacao('Não foi possível excluir o produto.','erro');return false}setProdutos(p=>p.filter(x=>x.id!==id));return true};
 const criarReceita=async(d:Omit<Receita,'id'>)=>{if(!sessao?.tenantId)return false;const {data,error}=await supabase.from('receitas').insert({...receitaParaBanco(d),tenant_id:sessao.tenantId}).select().single();if(error||!data){adicionarNotificacao('Erro ao salvar receita.','erro');return false}if(d.ingredientes.length)await supabase.from('receita_ingredientes').insert(d.ingredientes.map(i=>({receita_id:data.id,produto_id:i.produtoId,tipo:i.tipo,qtd:i.qtd})));setReceitas(p=>[...p,receitaDoBanco(data,d.ingredientes)]);return true};
 const excluirReceita=async(id:string)=>{const {error}=await supabase.from('receitas').delete().eq('id',id);if(error){adicionarNotificacao('Não foi possível excluir a receita.','erro');return false}setReceitas(p=>p.filter(x=>x.id!==id));return true};
 const darBaixa=async(id:string,tipo:'ML'|'Unidade',qtd:number)=>{const p=produtos.find(x=>x.id===id);if(!p||qtd<=0){adicionarNotificacao('Quantidade inválida para baixa.','erro');return false}const desconto=tipo==='ML'&&p.mlPorGarrafa>0?qtd/p.mlPorGarrafa:qtd;if(p.qtd-desconto<0){adicionarNotificacao(`Estoque insuficiente para ${p.nome}.`,'erro');return false}return atualizarProduto({...p,qtd:Number((p.qtd-desconto).toFixed(3))})};
 const registrarVenda=async(v:Omit<Venda,'id'>)=>{const p=produtos.find(x=>x.nome===v.nome);if(!p){adicionarNotificacao('Produto da venda não encontrado.','erro');return false}const tenant_id=sessao?.tenantId;if(!tenant_id){adicionarNotificacao('Sessão sem tenant válido.','erro');return false}const {data,error}=await supabase.from('vendas').insert({tenant_id,usuario_id:sessao?.id,total_venda:v.preco,custo_total:v.custo,lucro_total:v.lucro}).select().single();if(error||!data){adicionarNotificacao('Erro ao registrar venda.','erro');return false}await supabase.from('venda_itens').insert({tenant_id,venda_id:data.id,item_tipo:'produto',produto_id:p.id,nome_snapshot:p.nome,preco_unitario:p.preco,custo_unitario:p.precoCusto,quantidade:v.quantidade??1});setVendas(xs=>[vendaDoBanco(data),...xs]);return true};
 const entrar=async(email:string,senha:string)=>{const {error}=await supabase.auth.signInWithPassword({email,password:senha});if(error){adicionarNotificacao('E-mail ou senha inválidos.','erro');return false}await carregar();return true};const sair=async()=>{await supabase.auth.signOut();setSessao(null)};
 return <AppContext.Provider value={{produtos,receitas,vendas,carregando,erroConexao,sessao,notificacoes,setNotificacoes,adicionarNotificacao,nomeProdutoExiste,criarProduto,atualizarProduto,excluirProduto,criarReceita,excluirReceita,darBaixa,registrarVenda,entrar,sair}}>{children}</AppContext.Provider>;
}
export function useApp(){const ctx=useContext(AppContext);if(!ctx)throw new Error('useApp precisa ser usado dentro de AppProvider');return ctx}
